name: Clean Data and Run ANOFM Scraper

on:
  push:
    branches:
      - main  # You may adjust this according to the branches you use
  schedule:
    - cron: '30 18 * * *'  # Executes daily at 18:30 UTC
  workflow_dispatch:

jobs:
  clean_data:
    name: Clean Data using JMeter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run JMeter on GitHub Actions
        uses: sebiboga/run-jmeter-github-action@v0.0.6
        # Include any required configuration for JMeter action here
        # with:
        #   example-input: value

  anofm_scraper:
    name: ANOFM Scraper
    needs: clean_data  # Ensures that this job starts only after clean_data job is completed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Nim
        uses: iffy/install-nim@v5
        with:
          version: 'stable'

      - name: Install dependencies
        run: nimble install -y

      - name: Compile and Run
        run: nim compile --run --verbosity:0 src/anofmcrawl.nim
        env:
          API_KEY: ${{ secrets.API_KEY }}
