name: anofm nim crawler

on:
  push:
  schedule:
    - cron: '30 18 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Setup Nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: 'stable'

      - name: Instal dependencies
        run: nimble install -y

      # Runs a set of commands using the runners shell
      - name: Compile
        run: nim compile --run --verbosity:0 src/anofmcrawl.nim
        env:
          API_KEY: ${{ secrets.API_KEY }}
